[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
algorithms = { git = "https://github.com/a-isaiahharvey/algorithms-rs", branch = "main" }
rayon = "1.8"
